version: '3.8'

services:
  web:
    build: .
    ports:
      - "8020:8020"
    environment:
      - DJANGO_SETTINGS_MODULE=nishadparty.settings
      - DJANGO_ENV=production
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
