# Generated by Django 5.0 on 2025-09-05 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                ("metric_value", models.JSONField()),
                ("constituency", models.CharField(blank=True, max_length=100)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("date_recorded", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("USER", "User Metrics"),
                            ("DONATION", "Donation Metrics"),
                            ("CAMPAIGN", "Campaign Metrics"),
                            ("ENGAGEMENT", "Engagement Metrics"),
                            ("FINANCIAL", "Financial Metrics"),
                            ("GEOGRAPHIC", "Geographic Metrics"),
                        ],
                        max_length=20,
                    ),
                ),
                ("additional_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_recorded"],
                "unique_together": {("metric_name", "date_recorded", "constituency")},
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("CHART", "Chart Widget"),
                            ("COUNTER", "Counter Widget"),
                            ("TABLE", "Table Widget"),
                            ("MAP", "Map Widget"),
                            ("PROGRESS", "Progress Bar Widget"),
                            ("LIST", "List Widget"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("configuration", models.JSONField()),
                ("position", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("size", models.CharField(default="medium", max_length=20)),
                ("refresh_interval", models.IntegerField(default=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
