# Generated by Django 5.0 on 2025-09-05 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "asset_code",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("VEHICLE", "Vehicle"),
                            ("EQUIPMENT", "Equipment"),
                            ("ELECTRONICS", "Electronics"),
                            ("FURNITURE", "Furniture"),
                            ("BOAT", "Boat"),
                            ("SOUND_SYSTEM", "Sound System"),
                            ("TENT", "Tent"),
                            ("BANNER", "Banner"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("purchase_date", models.DateField()),
                ("purchase_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_location", models.CharField(max_length=200)),
                ("constituency", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_USE", "In Use"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("DAMAGED", "Damaged"),
                            ("RETIRED", "Retired"),
                            ("LOST", "Lost"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                            ("DAMAGED", "Damaged"),
                        ],
                        default="GOOD",
                        max_length=20,
                    ),
                ),
                ("maintenance_schedule", models.JSONField(default=dict)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("warranty_expiry", models.DateField(blank=True, null=True)),
                ("insurance_details", models.JSONField(default=dict)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("model_number", models.CharField(blank=True, max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="asset_images/"),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="asset_qr_codes/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AssetCheckout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checkout_date", models.DateTimeField()),
                ("expected_return_date", models.DateTimeField()),
                ("actual_return_date", models.DateTimeField(blank=True, null=True)),
                ("purpose", models.CharField(max_length=200)),
                ("destination", models.CharField(blank=True, max_length=200)),
                (
                    "condition_checkout",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                            ("DAMAGED", "Damaged"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condition_return",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                            ("DAMAGED", "Damaged"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "gps_latitude_checkout",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_longitude_checkout",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                (
                    "gps_latitude_return",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_longitude_return",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("checkout_notes", models.TextField(blank=True)),
                ("return_notes", models.TextField(blank=True)),
                ("is_returned", models.BooleanField(default=False)),
                ("is_overdue", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_checkouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkouts",
                        to="assets.asset",
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-checkout_date"],
            },
        ),
        migrations.CreateModel(
            name="AssetMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=8)),
                ("maintenance_date", models.DateField()),
                ("performed_by", models.CharField(max_length=200)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("parts_replaced", models.JSONField(default=list)),
                ("before_images", models.JSONField(default=list)),
                ("after_images", models.JSONField(default=list)),
                (
                    "warranty_period",
                    models.IntegerField(default=0, help_text="Warranty period in days"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-maintenance_date"],
            },
        ),
        migrations.CreateModel(
            name="GatePass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pass_code", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="gate_passes/"),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("VIP", "VIP Access"),
                            ("GENERAL", "General Access"),
                            ("VOLUNTEER", "Volunteer Access"),
                            ("STAFF", "Staff Access"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("entry_gate", models.CharField(blank=True, max_length=50)),
                ("special_instructions", models.TextField(blank=True)),
                ("companion_count", models.IntegerField(default=0)),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_passes",
                        to="campaigns.event",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_gate_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
                "unique_together": {("event", "attendee")},
            },
        ),
    ]
