# Generated by Django 5.0 on 2025-09-06 05:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assetcheckout",
            name="is_overdue",
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="acceptance_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_asset_checkouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="assignment_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="damage_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="damage_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="damage_reported",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="rejection_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Acceptance"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("IN_USE", "In Use"),
                    ("RETURNED", "Returned"),
                    ("OVERDUE", "Overdue"),
                    ("LOST", "Lost/Damaged"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assetcheckout",
            name="user_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="assetcheckout",
            name="checked_out_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_checkouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="assetcheckout",
            name="checkout_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assetcheckout",
            name="condition_checkout",
            field=models.CharField(
                choices=[
                    ("EXCELLENT", "Excellent"),
                    ("GOOD", "Good"),
                    ("FAIR", "Fair"),
                    ("POOR", "Poor"),
                    ("DAMAGED", "Damaged"),
                ],
                default="GOOD",
                max_length=20,
            ),
        ),
    ]
