# Generated by Django 4.2.7 on 2025-10-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("hi", "Hindi"), ("en", "English")], default="hi", max_length=5
            ),
        ),
    ]
