# Generated by Django 5.0 on 2025-10-13 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_managers_alter_user_preferred_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("USER_MANAGEMENT", "User Management"),
                            ("ASSET_MANAGEMENT", "Asset Management"),
                            ("GATE_PASS", "Gate Pass Management"),
                            ("DONATION_MANAGEMENT", "Donation Management"),
                            ("EVENT_MANAGEMENT", "Event Management"),
                            ("MEMBERSHIP_MANAGEMENT", "Membership Management"),
                        ],
                        max_length=50,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this permission"
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permissions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Permission",
                "verbose_name_plural": "Feature Permissions",
                "ordering": ["-granted_at"],
                "unique_together": {("user", "feature")},
            },
        ),
    ]
