# Generated by Django 5.0 on 2025-09-05 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("LEADERSHIP", "Leadership Meeting"),
                            ("COORDINATION", "Coordination Meeting"),
                            ("PLANNING", "Planning Session"),
                            ("REVIEW", "Review Meeting"),
                            ("STRATEGY", "Strategy Discussion"),
                            ("COMMUNITY", "Community Meeting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("duration_minutes", models.IntegerField()),
                ("venue", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                ("is_virtual", models.BooleanField(default=False)),
                ("meeting_link", models.URLField(blank=True)),
                ("constituency", models.CharField(blank=True, max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("POSTPONED", "Postponed"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("agenda", models.JSONField(default=list)),
                ("materials", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date_time"],
            },
        ),
        migrations.CreateModel(
            name="MeetingAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ORGANIZER", "Organizer"),
                            ("REQUIRED", "Required Attendee"),
                            ("OPTIONAL", "Optional Attendee"),
                            ("RESOURCE", "Resource Person"),
                        ],
                        default="REQUIRED",
                        max_length=20,
                    ),
                ),
                ("invitation_sent", models.BooleanField(default=False)),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("TENTATIVE", "Tentative"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                ("response_notes", models.TextField(blank=True)),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "unique_together": {("meeting", "attendee")},
            },
        ),
    ]
