# Generated by Django 5.0 on 2025-09-05 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("donor_name", models.CharField(max_length=100)),
                ("donor_email", models.EmailField(max_length=254)),
                ("donor_phone", models.CharField(max_length=15)),
                ("donor_address", models.TextField(blank=True)),
                ("donor_pan", models.CharField(blank=True, max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online Payment"),
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("DD", "Demand Draft"),
                            ("UPI", "UPI"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=100)),
                ("razorpay_order_id", models.CharField(blank=True, max_length=100)),
                ("razorpay_signature", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                ("constituency", models.CharField(blank=True, max_length=100)),
                ("purpose", models.CharField(blank=True, max_length=200)),
                ("anonymous", models.BooleanField(default=False)),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("receipt_generated", models.BooleanField(default=False)),
                (
                    "receipt_file",
                    models.FileField(blank=True, null=True, upload_to="receipts/"),
                ),
                ("tax_exemption_claimed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "raised_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="campaign_images/"
                    ),
                ),
                ("constituency", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationCompliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pan_verified", models.BooleanField(default=False)),
                ("pan_verification_date", models.DateTimeField(blank=True, null=True)),
                ("election_commission_reported", models.BooleanField(default=False)),
                ("ec_report_date", models.DateTimeField(blank=True, null=True)),
                ("ec_reference_number", models.CharField(blank=True, max_length=50)),
                ("compliance_notes", models.TextField(blank=True)),
                (
                    "verification_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance_docs/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donations.donation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurringDonation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("HALF_YEARLY", "Half Yearly"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("next_payment_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("failed_attempts", models.IntegerField(default=0)),
                ("max_failures", models.IntegerField(default=3)),
                ("constituency", models.CharField(blank=True, max_length=100)),
                ("purpose", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
