# Generated by Django 5.0 on 2025-09-05 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GatePass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pass_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("visitor_name", models.CharField(max_length=100)),
                ("visitor_phone", models.CharField(max_length=15)),
                ("visitor_email", models.EmailField(blank=True, max_length=254)),
                (
                    "visitor_id_proof",
                    models.CharField(help_text="ID proof number", max_length=50),
                ),
                (
                    "company_organization",
                    models.CharField(
                        blank=True,
                        help_text="Company/Organization name",
                        max_length=200,
                    ),
                ),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("VISITOR", "Visitor Pass"),
                            ("VENDOR", "Vendor Pass"),
                            ("VIP", "VIP Pass"),
                            ("STAFF", "Staff Pass"),
                            ("EMERGENCY", "Emergency Pass"),
                        ],
                        default="VISITOR",
                        max_length=20,
                    ),
                ),
                ("purpose", models.TextField(help_text="Purpose of visit")),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                (
                    "authorized_areas",
                    models.TextField(
                        blank=True, help_text="Areas visitor is authorized to access"
                    ),
                ),
                ("escort_required", models.BooleanField(default=False)),
                ("escort_name", models.CharField(blank=True, max_length=100)),
                ("escort_phone", models.CharField(blank=True, max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_gatepasses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_gatepasses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gate Pass",
                "verbose_name_plural": "Gate Passes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GatePassLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("details", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "gatepass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="gatepass.gatepass",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gate Pass Log",
                "verbose_name_plural": "Gate Pass Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GatePassPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_create_gatepass", models.BooleanField(default=False)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gatepass_permission",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gate Pass Permission",
                "verbose_name_plural": "Gate Pass Permissions",
            },
        ),
    ]
