# Generated by Django 5.0 on 2025-09-05 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("content", models.TextField()),
                ("excerpt", models.TextField()),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="articles/"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NEWS", "News"),
                            ("ANNOUNCEMENT", "Announcement"),
                            ("POLICY", "Policy"),
                            ("COMMUNITY", "Community Stories"),
                            ("FISHING", "Fishing Related"),
                            ("SCHEMES", "Government Schemes"),
                            ("EVENTS", "Events"),
                            ("PRESS_RELEASE", "Press Release"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hi", "Hindi"),
                            ("en", "English"),
                            ("bho", "Bhojpuri"),
                            ("awa", "Awadhi"),
                            ("mag", "Magahi"),
                            ("mai", "Maithili"),
                            ("bn", "Bengali"),
                            ("as", "Assamese"),
                            ("or", "Odia"),
                            ("gu", "Gujarati"),
                        ],
                        default="hi",
                        max_length=5,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("tags", models.JSONField(default=list)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("constituency", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_file", models.FileField(upload_to="voice_messages/")),
                ("transcript", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hi", "Hindi"),
                            ("en", "English"),
                            ("bho", "Bhojpuri"),
                            ("awa", "Awadhi"),
                            ("mag", "Magahi"),
                            ("mai", "Maithili"),
                            ("bn", "Bengali"),
                            ("as", "Assamese"),
                            ("or", "Odia"),
                            ("gu", "Gujarati"),
                        ],
                        default="hi",
                        max_length=5,
                    ),
                ),
                ("duration_seconds", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ANNOUNCEMENT", "Announcement"),
                            ("GREETINGS", "Greetings"),
                            ("TESTIMONIAL", "Testimonial"),
                            ("COMPLAINT", "Complaint"),
                            ("SUGGESTION", "Suggestion"),
                            ("SUPPORT", "Support Request"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Moderation"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_type", models.CharField(max_length=50)),
                ("object_id", models.PositiveIntegerField()),
                ("field_name", models.CharField(max_length=50)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hi", "Hindi"),
                            ("en", "English"),
                            ("bho", "Bhojpuri"),
                            ("awa", "Awadhi"),
                            ("mag", "Magahi"),
                            ("mai", "Maithili"),
                            ("bn", "Bengali"),
                            ("as", "Assamese"),
                            ("or", "Odia"),
                            ("gu", "Gujarati"),
                        ],
                        max_length=5,
                    ),
                ),
                ("translated_text", models.TextField()),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "translated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("content_type", "object_id", "field_name", "language")
                },
            },
        ),
    ]
