# Generated by Django 4.2.7 on 2025-10-04 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("youtube_url", models.URLField(blank=True, null=True)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="videos/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="videos/thumbnails/"
                    ),
                ),
                ("duration_minutes", models.IntegerField(default=0)),
                ("duration_seconds", models.IntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SPEECHES", "Speeches"),
                            ("CAMPAIGNS", "Campaigns"),
                            ("EVENTS", "Events"),
                            ("DOCUMENTARIES", "Documentaries"),
                            ("INTERVIEWS", "Interviews"),
                            ("NEWS", "News Coverage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("speaker", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="photos/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/thumbnails/"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CAMPAIGNS", "Campaigns"),
                            ("EVENTS", "Events"),
                            ("COMMUNITY", "Community"),
                            ("MEETINGS", "Meetings"),
                            ("LEADERSHIP", "Leadership"),
                            ("RALLIES", "Rallies"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("photographer", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
